### ISSUE TITLE
[QUESTION] why do we need a `dpo_train_step`?

### ISSUE THREAD

**Issue by loofahcus** [alibaba/ChatLearn#143]
https://github.com/alibaba/ChatLearn/blob/main/examples/megatron/models/base_trainer.py#L149

The only difference between `megatron_train_step` and `dpo_train_step` is:
```python
        if config.pipeline_model_parallel_size > 1:
            micro_batch_size *= 2
```
So my question is why do we need to do this?

**Comment by charles9304** [comment]
For dpo trainer, each sample contains "chosen_ids" and "rejected_ids", which are learned to rank  "chosen_response" before "rejected_response". We concat chosen_ids and reject_ids first, which doubles micro_batch_size for forwarding.
When applying pipeline parallelism, megatron defines and reuses the  buffer to transfer data among stages. Thus the buffer need to be defined with real micro_batch_size.

https://github.com/alibaba/ChatLearn/blob/main/examples/megatron/models/policy_trainer.py#L554
