### ISSUE TITLE
[Feature] moe框架的模型为何需要单独支持？

### ISSUE THREAD

**Issue by yiyepiaoling0715** [alibaba/ChatLearn#158]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

￼
https://github.com/alibaba/ChatLearn/tree/main
chatlearn框架，为何moe需要单独支持，如果直接将llama等模型替换为moe模型比如deepseek-v2 进行训练，会有什么问题么

**Comment by adoda** [comment]
如果你跑一个小规模moe模型，不需要特别的并行策略，这种会比较简单。如果你跑更大规模，训练开启EP，推理不开启，就需要额外支持。
