### ISSUE TITLE
[Feature] dpo场景 为什么 onlinedpo效果不如dpo，rlhf会有下降？

### ISSUE THREAD

**Issue by yiyepiaoling0715** [alibaba/ChatLearn#159]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/user-attachments/assets/c506c56f-c791-4263-96de-6c22a2b0eb0a)

**Comment by adoda** [comment]
开源HH数据集中没有coding相关数据，这块效果会比较随机。这里关注avg指标即可。生产训练中，可以按需准备训练数据。
