### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yiyepiaoling0715** [alibaba/ChatLearn#170]
**Describe the bug**
`  File "/lpai/code/ChatLearn/chatlearn/tools/megatron_checkpoint_utils.py", line 281, in <module>
    from tools.checkpoint import loader_mcore, saver_mcore,schema_mcore # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lpai/code/ChatLearn/chatlearn/tools/megatron_checkpoint_utils.py", line 249, in load_module
    exec(codeobj, module.__dict__)  # pylint: disable=exec-used
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lpai/code/megatron-lm/tools/checkpoint/loader_mcore.py", line 9, in <module>
    from schema_mcore import get_model_schema
ModuleNotFoundError: No module named 'schema_mcore'`
**To Reproduce**
启动脚本
`export MEGATRON=/user/code/megatron-lm
export CHATLEARN=/user/code/ChatLearn

cd ${CHATLEARN}/examples/megatron/
export PYTHONPATH=/lpai/code/megatron-lm/tools/checkpoint:$PYTHONPATH

#对于llama2-7B的模型，我们会将模型转换成 TP (tensor_model_parallel_size)=4，PP (pipeline_model_parallel_size)=1 的 checkpoint, 模型会存放在SAVE_PATH中。
#对于llama2-13B的模型，我们会将模型转化成 TP=8，PP=1 的 checkpoint。
#对于llama2-70B的模型，我们会将模型转化成 TP=8，PP=4 的 checkpoint。

TP=8 
PP=1
export LOAD_PATH=/user/volumes/jfs-sc-ep-lf/data/multitask_best_ft/202411060720/best_model/full/
#todo
export TOKENIZER_MODEL=$LOAD_PATH/tokenizer.json 
export SAVE_PATH=/user/volumes/jfs-sc-ep-lf/data/rl_tmp

bash /user/code/ChatLearn/examples/megatron/scripts/convert_hf_to_megatron.sh`
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by haolin-nju** [comment]
What is `schema_mcore`? BTW, please add a proper title to this issue :)

**Comment by uygnef** [comment]
checkout megatron to core_r0.8.0

**Comment by haolin-nju** [comment]
Closing this issue due to a long period of inactivity. If there are any other problems, feel free to reopen the issue at any time. :)
