### ISSUE TITLE
[BUG] AttributeError: 'VLLMPolicyInference' object has no attribute 'cached_scheduler_outputs'

### ISSUE THREAD

**Issue by uygnef** [alibaba/ChatLearn#179]
**Describe the bug**
run samples code use scripts/train_rlhf_llama.sh， vllm version 0.5.1
```
【2024-12-13 15:37:21】[36m(VLLMPolicyInference pid=13628, ip=10.66.159.53)[0m File "/nfs/volume-1555/ChatLearn/chatlearn/models/vllm_module.py", line 672, in generate_vllm
【2024-12-13 15:37:21】[36m(VLLMPolicyInference pid=13628, ip=10.66.159.53)[0m cached_outputs = self.cached_scheduler_outputs[virtual_engine]
【2024-12-13 15:37:21】[36m(VLLMPolicyInference pid=13628, ip=10.66.159.53)[0m ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
【2024-12-13 15:37:21】[36m(VLLMPolicyInference pid=13628, ip=10.66.159.53)[0m AttributeError: 'VLLMPolicyInference' object has no attribute 'cached_scheduler_outputs'
```
I was reviewing the vllm source code for version 0.5.1 ([link](https://github.com/vllm-project/vllm/blob/v0.5.1/vllm/engine/llm_engine.py)) and noticed that the cached_scheduler_outputs method is missing. Upon further investigation, I found that the ChatLearn repository ([link](https://github.com/alibaba/ChatLearn/blob/main/chatlearn/models/vllm_module.py#L329)) includes a create_cached_scheduler_outputs method for vllm version 0.6.3.

Should I copy this method into my version 0.5.1 codebase to add the missing functionality? If so, are there any compatibility concerns I should be aware of?

**To Reproduce**
sh scripts/train_rlhf_llama.sh

**Comment by tkqie** [comment]
hello, i met the same issue, is this still been unsolved? Should vllm be updated to 0.6.3?

**Comment by uygnef** [comment]
@

> hello, i met the same issue, is this still been unsolved? Should vllm be updated to 0.6.3?

 `git checkout v1.0.2` solve the issue

**Comment by tkqie** [comment]
> @tkqie
> 
> > hello, i met the same issue, is this still been unsolved? Should vllm be updated to 0.6.3?
> 
> `git checkout v1.0.2` solve the issue

Thx, this worked for me too
