### ISSUE TITLE
about reward model LOAD_PATH=path-to-sft-ckpt

### ISSUE THREAD

**Issue by carrot0117** [alibaba/ChatLearn#188]
May I ask, to which level of the directory does the load path refer? Is it up to the hh_sft level or the iter00001000 level mentioned in the previous line?
![image](https://github.com/user-attachments/assets/20f5fbfc-1d32-4e57-aac6-a5bdf22c9ca3)
![image](https://github.com/user-attachments/assets/a2ed8c51-042f-42df-9fb5-67efec426eb2)

**Comment by adoda** [comment]
the hh_sft level.

**Comment by carrot0117** [comment]
thanks for your reply!
